### ISSUE TITLE
Add ignore these "bad" characters

### ISSUE THREAD

**Issue by crystalfp** [WengerK/vscode-highlight-bad-chars#10]
Thanks for the extension. I would like to ask to add a "ignore these characters" setting. The character listed there are not marked as bad characters.

Rationale: I use VSCode also to edit markdown text. Here I want to see for example ﬀ (ff ligature, resulting often from PDF conversion) and special spaces, but not – (en dash) or « » used through the text.

Thanks for considering!
mario

**Comment by teresaejunior** [comment]
This would be very useful. For example, characters like \u200d are needed in Devanagari text: https://en.wikipedia.org/wiki/Zero-width_joiner

**Comment by jwssnr** [comment]
I agree. That would be awesome. 
@ohanhi did this for Atom.

**Comment by jwssnr** [comment]
... and I would buy you a large amount of 🍺.

**Comment by waldyrious** [comment]
Hi @crystalfp — could you keep this issue open for those of us who still use this extension? You can unsubscribe from it in the sidebar, so that any future updates won't bother you anymore.
