### ISSUE TITLE
[Feature Request] Purge Command Palette please

### ISSUE THREAD

**Issue by Pablion** [WengerK/vscode-highlight-bad-chars#15]
## Feature Request
Remove the "Hello World" from the Command Palette.

## Reproduce
1. Activate the extension
2. Open Command Palette
3. Type Hello World

**Comment by ItalyPaleAle** [comment]
Closed via #16, thanks for creating a PR!

**Comment by Pablion** [comment]
No problem! You've helped me more than I did you.
