### ISSUE TITLE
Does not match SOFT HYPHEN

### ISSUE THREAD

**Issue by emkayy** [WengerK/vscode-highlight-bad-chars#17]
The extension does not recognise soft hypens \u00AD (&shy;).
However, I would regard "not visible" characters most important to show.
Could you please enable all unicode characers?

**Comment by emkayy** [comment]
You can use https://github.com/nhoizey/vscode-gremlins
Since this extension seems like it's not updated anymore for years

**Comment by ItalyPaleAle** [comment]
Confirm it's working for me. Can you double-check that you've updated your extension?
