### ISSUE TITLE
Tab character showing as bad character

### ISSUE THREAD

**Issue by mattvrydaghs** [WengerK/vscode-highlight-bad-chars#21]
Since the latest update, the tab character is being highlighted as a bad character. Since tab is my preferred indentation method, this is rather annoying.

Mousing over the highlight shows "Bad char \u9 ( )"

On Latest VS Code (1.60.2) on MacOS (Intel) 10.15.1

**Comment by WengerK** [comment]
Working on a fix

**Comment by WengerK** [comment]
release 0.0.5 should fix this.

Thanks to @ItalyPaleAle for the quick fix !

**Comment by mattvrydaghs** [comment]
Thanks for the quick response all! Updated and confirmed fixed!

**Comment by ItalyPaleAle** [comment]
I'm very sorry folks. I promise it wasn't me trying to impose spaces over tabs (although who doesn't have an opinion? 😂). just accidentally including all control characters and didn't test with a file with tabs.

Sorry again about that, hope the fix rolls out soon.
