### ISSUE TITLE
Non Breaking Space

### ISSUE THREAD

**Issue by scotthardwick** [WengerK/vscode-highlight-bad-chars#6]
Kevin,
Thanks for the great extension!

I often paste in code from Microsoft Word, so adding these items in the settings for your extension made my life so much easier:
"\u2013", //EN Dash
"\u2014", //EM Dash
"\u2018", //Left Single Quotation Mark
"\u2019", //Right Single Quotation Mark
"\u201C", //Left Double Quotation Mark
"\u201D", //Right Double Quotation Mark
"\u2026"  //Horizontal Ellipsis

One question/request though, I have not found a way to get it to highlight a non-breaking space (Ctrl+Shift+Space in MS Word) which I think should be
"\u00A0"  // non-breaking space

Any thoughts?

**Comment by WengerK** [comment]
It should highlight nbsp, I often type them & it highlights it. Did you find out how to resolve your issue ?

**Comment by ItalyPaleAle** [comment]
This is included on https://github.com/WengerK/vscode-highlight-bad-chars/blob/master/src/extension.ts#L27
