### ISSUE TITLE
Feature request: setting for all non-ascii characters

### ISSUE THREAD

**Issue by halaaro** [WengerK/vscode-highlight-bad-chars#7]
Ran into problem where a bad UTF-8 character showed up in the configuration file but was not highlighted. 

Instead of trying to specify all "bad" characters, it would be nice if there was a setting to highlight all non-ascii characters or somehow a provide a short list of "good" characters. 

I used this to clean up my config files:
```js
let charRegExp = '[^' + aciiChars.join('') + ']';
```

**Comment by ssbarnea** [comment]
I ended up with this extension especially for trying to find the "culprit" Unicode characters that breaks the code.

Sadly the extension is not yet able to deliver on this and I do not know a way to do it yet.
