### ISSUE TITLE
Highlight zero-width chars as well

### ISSUE THREAD

**Issue by fabb** [WengerK/vscode-highlight-bad-chars#9]
Yesterday I had a [`0x1d` unicode character](http://www.fileformat.info/info/unicode/char/1d/index.htm) in the middle of some css class name string, and it took me ages to find that out. No idea how it landed there. I finally found it because I pasted the string in Sublime text which shows special unicode characters with their code point like this:
<img width="72" alt="screenshot 2018-12-05 at 08 29 13" src="https://user-images.githubusercontent.com/153960/49497152-f1fcda00-f867-11e8-83db-ab3c4e51aaef.png">

The Highilght Bad Chars extension unfortunately would not highlight or show this character. Could that functionality be added, or is that rather something for another extension?

**Comment by fabb** [comment]
I managed to make the control character visible by activating VSCode setting `"editor.renderControlCharacters": true`.
Leaving this open for further comments, maybe there are other characters that are not caught by this.

**Comment by williamdenton** [comment]
i've found a pesky 0x7F (DEL) char in a json document. This extension plus the tip above for rendering control characters makes _something_ visible, but it would be nice to have something that told you want it was. 
![image](https://user-images.githubusercontent.com/7498040/109441295-cc3bfb00-7a99-11eb-9994-179c3b67f8f8.png)


Ended up pasting the string into this website to see it - https://www.soscisurvey.de/tools/view-chars.php


![image](https://user-images.githubusercontent.com/7498040/109441279-bfb7a280-7a99-11eb-9218-eb89e8c7cc3e.png)
